### PR TITLE
remove legacy fabric-video template for all platforms

### PR DESCRIPTION
**Pull request by dskamiotis**
## What does this change?
As part of the migration process of templates to Svelte, we have successfully migrated the fabric-video template, as confirmed in the [migrate fabric-video PR](https://github.com/guardian/commercial-templates/pull/410). This PR removes the legacy fabric-video template.

## How to test
Run `pnpm build` followed by `pnpm preview` to verify that the fabric-video template link is no longer available in the Legacy section.

## How can we measure success?
Success can be measured by ensuring that all legacy code related to the fabric-video template is removed without any adverse effects on current templates. Additionally, the fabric-video template link should no longer be visible in the Legacy section of the test sandbox.

## Images
| Before |  After (fabric-video removed |
|-------|--------|
| Screenshot 2024-12-12 at 11 40 58| Screenshot 2024-12-12 at 11 44 21 |

## Accessibility

-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

### CODE REVIEW

**Review by deedeeh — APPROVED** [review]
It's great to get rid of the legacy ones!

**Review by emma-imber — COMMENTED** [review]
Are there separate native styles in GAM for the AMP/app templates that need to be checked here?

**Comment by dskamiotis** [comment]
> tyles in GAM for the AMP/app templates that need to be check



> Are there separate native styles in GAM for the AMP/app templates that need to be checked here?

I’ve checked all the fabric-video native templates in GAM and confirmed that the 'Device Category' is set to All devices. There aren’t any platform-specific overrides or AMP/app-specific settings that depend on the fabric-video template AFAICS.
Is this still ok to merge? @emma-imber

**Comment by emma-imber** [comment]
> > tyles in GAM for the AMP/app templates that need to be check
> 
> > Are there separate native styles in GAM for the AMP/app templates that need to be checked here?
> 
> I’ve checked all the fabric-video native templates in GAM and confirmed that the 'Device Category' is set to All devices. There aren’t any platform-specific overrides or AMP/app-specific settings that depend on the fabric-video template AFAICS. Is this still ok to merge? @emma-imber

Should be ok in that case, thanks for checking!

**Review by emma-imber — APPROVED** [review]

**Pull request merged**
