### PR TITLE
Hosted By - AMP traffic driver cards

### PR DESCRIPTION
**Pull request by lps88**
New template:
[Example](https://amp.theguardian.com/sport/blog/2016/nov/20/andy-murray-fights-fatigue-with-fire-to-end-2016-in-blistering-fashion?adtest=lydia2)
[DFP Native Style](https://www.google.com/dfp/59666047#delivery/CreateNativeAdFormatAndStyle/nativeStyleId=84510&creativeTemplateId=10074567)
[Creative](https://www.google.com/dfp/59666047#delivery/PreviewCreative/orderId=341470047&lineItemId=142466367&creativeId=105380421687)

image
image

### CODE REVIEW

**Comment by Calanthe** [comment]
Is there any border around the ad?

**Comment by lps88** [comment]
It's the same design as the [old one](https://www.theguardian.com/uk/technology?adtest=demo_hosted):
image

**Comment by Calanthe** [comment]
But the old one has a slightly yellow background colour.

**Comment by Calanthe** [comment]
👍

**Comment by lps88** [comment]
@regiskuckaertz Would you like to review this?

**Pull request merged**
