### PR TITLE
Changed hex code

### PR DESCRIPTION
**Pull request by RobertFreeman**

### CODE REVIEW

**Comment by shtukas** [comment]
That's a *small* change :) What for ?

**Comment by RobertFreeman** [comment]
Ha, I know - I just wanted to check I could do it!

**Comment by shtukas** [comment]
@RobertFreeman That's what I thought. One's first PR is an event that needs to be treasured and celebrated :)

**Comment by sndrs** [comment]
is the the correct colour though? WHAT HAVE I APPROVED!!

**Comment by shtukas** [comment]
@sndrs You approved `#b51801` !!

**Pull request merged**
