### PR TITLE
Context-specific templates

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Lots of stuff in this PR:

- moving all existing templates to a `/web` subfolder, so that app- and AMP-specific templates can go in `/app` and `/amp` respectively
- updating the build and preview process to take that into account
- removing some duplicate stuffi in the CAPI image handling
- adding an app-specific Fabric
- adding an app-specific Traffic Driver

### CODE REVIEW

**Comment by lps88** [comment]
Cool 👍

**Comment by regiskuckaertz** [comment]
[Glabs Traffic Driver for iOS, Android and AMP](https://trello.com/c/DzYaV57z/142-glabs-traffic-driver-for-ios-android-and-amp)

**Comment by regiskuckaertz** [comment]
[Fabric for iOS and Android](https://trello.com/c/66MPuQ7K/144-fabric-for-ios-and-android)

**Comment by regiskuckaertz** [comment]
[Fork native templates to allow web/app/AMP specific versions](https://trello.com/c/PTDtJPWN/145-fork-native-templates-to-allow-web-app-amp-specific-versions)

**Pull request merged**
